...

diff --git a/latest b/latest
--- a/latest
+++ b/latest
@@ -55,4 +55,14 @@ x mkdirp "$___X_CMD_PKG_RAWPATH" "$___X_CMD_PKG_DOWNLOAD_PATH" "$___X_CMD_PKG_IN
 #     ___X_CMD_PKG_DOWNLOAD_PATH  "$___X_CMD_ROOT_TMP/pkg/download" \
 #     ___X_CMD_PKG_INSTALL_PATH   "$___X_CMD_ROOT_TMP/pkg/installed"
 
+___x_cmd_pkg__smoke(){
+    (
+    cd "$___X_CMD_PKG_RAWPATH" || return
+    if  ! . "./"*"/$name/.x-cmd/smoke.sh" ; then
+        pkg:error "source smoke.sh failed"
+    fi
+    )
+}
+
+
 xrc setmain ___x_cmd_pkg
