...

diff --git a/v0 b/v0
--- a/v0
+++ b/v0
@@ -31,13 +31,8 @@ static_build_which(){
 
         static_build_log info "Downloading: ${repo}/bin/$exe.7z"
 
-        local url="https://gitee.com/static-build/${repo}/raw/main/bin/$exe.7z"
-        if [ "$___X_CMD_IN_CHINA_NET" != 1 ]; then
-            url="https://raw.githubusercontent.com/static-build/${repo}/main/bin/$exe.7z"
-        fi
-
-        if ! CACHE="$target/$exe.7z" ___x_cmd_curl "$url"; then
-            static_build_log warn "Download failure: $url"
+        if ! ___x_cmd_curl_gitx static-build "${repo}" main "bin/$exe.7z" "$target/$exe.7z"; then
+            static_build_log warn "Download failure: $repo/main bin/$exe.7z"
             static_build_log warn "File Not Found. Perhaps the platform is NOT supported: $exe"
             return 1
         fi
@@ -62,7 +57,7 @@ static_build_which(){
                     for i in $(seq "$size"); do
                         # suffix="$(printf "%03s" "$i")" # Not work in gnu bash
                         suffix="$(printf "%3s" "$i" | tr " " 0)"
-                        if ! CACHE="$exe.7z.$suffix" ___x_cmd_curl "$url.$suffix" ; then
+                        if ! ___x_cmd_curl_gitx static-build "${repo}" main "bin/$exe.7z" "$target/$exe.7z.$suffix" "$exe.7z.$suffix"; then
                             static_build_log warn "Download failure in $exe.7z.$suffix" >&2
                             return 1
                         fi
