...

diff --git a/lib/download b/lib/download
--- a/lib/download
+++ b/lib/download
@@ -17,6 +17,13 @@ ___x_cmd_pkg_download(){
     local ball="$___X_CMD_PKG_DOWNLOAD_PATH/$pkg_name/$version.$file_suffix"
     pkg:debug "Download package url_list: $url_list ball: $ball"
 
+    local static_build
+    static_build="$(___x_cmd_pkg___attr "$@" "$osarch" static-build)"
+    if [ -n "$static_build" ]; then
+        ___x_cmd_pkg_download_file___from_static_build_and_deflate "${static_build%/*}" "${static_build#*/}"
+        return
+    fi
+
     local md5
     local sha1
     local sha256
@@ -31,7 +38,14 @@ ___x_cmd_pkg_download(){
         x rmrf "$ball"
     fi
     while read -r url; do
-        ___x_cmd_pkg_download_file "$url" "$ball" || return
+        # TODO: ___x_cmd_httpget support 302
+        # ___x_cmd_httpget "$url" "$ball" || {
+        pkg:info "Download package from $url to $ball"
+        curl --progress-bar --location --retry-max-time 10 --retry 0 "$url" --output "$ball" || {
+            pkg:warn "Fail to download from $url"
+            continue
+        }
+
         ! ___x_cmd_pkg_download___check_hashsum "$ball" "$md5" "$sha1" "$sha256" "$sha512" || return 0
 
         pkg:warn "File corrupted."
@@ -51,33 +65,6 @@ ___x_cmd_pkg_download_file(){
         *)                      pkg:error "Exit because of unknown URL: $url." >&2 ;;
     esac
 }
-
-___x_cmd_pkg_download_file_from_http(){
-    local url="${1:?Provide url}"
-    local ball="${2:?Provide ball}"
-
-    # TODO: ___x_cmd_httpget support 302
-    # ___x_cmd_httpget "$url" "$ball" || {
-    pkg:info "Download package from $url to $ball"
-    curl --progress-bar --location --retry-max-time 10 --retry 0 "$url" --output "$ball" || {
-        pkg:warn "Fail to download from $url"
-        return 1
-    }
-}
-
-___x_cmd_pkg_download_file_from_static_build(){
-    local url="${1:?Provide url}"
-    local ball="${2:?Provide ball}"
-
-    repo="${url#static-build://}"
-    exe="${url#*/}"
-    repo="${repo%%/*}"
-
-    target="${ball%/*}"
-
-    ___x_cmd_pkg_download_file___from_static_build_and_deflate "$repo" "$exe"
-}
-
 
 ___x_cmd_pkg_download_file___from_static_build_and_deflate(){
     local IFS='
