...

diff --git a/lib/install b/lib/install
--- a/lib/install
+++ b/lib/install
@@ -1,25 +1,53 @@
 
-___x_cmd_pkg_install___download(){
-    # get bin url
-    # download from url
-    :
+___x_cmd_pkg_download(){
+    local pkg_name="${1:?Provide pkg name}"
+    local version="${2:?rovide version}"
+
+    local url_list
+    url_list="$(___x_cmd_pkg___bin_url_list "$@")"
+
+    local url
+    local ball="$___X_CMD_PKG_DOWNLOAD_PATH/$pkg_name/$version"
+    while read -r url; do
+
+        # Check MD5Sum. Whether it is already exists
+        ___x_cmd_httpget "$url" "$ball" || {
+            pkg:warn "Fail to download from $url"
+            continue
+        }
+        # Check MD5Sum. If not. Deleted
+    done <<A
+$url_list
+A
+
 }
 
 # This is default
 ___x_cmd_pkg_install___unzip(){
-    :
+    local pkg_name="${1:?Provide pkg name}"
+    local version="${2:?rovide version}"
+
+    local ball="$___X_CMD_PKG_DOWNLOAD_PATH/$pkg_name/$version"
+    local tgt="$___X_CMD_PKG_INSTALL_PATH/$pkg_name/$version"
+
+    x uz "$ball" "$tgt" || {
+        pkg:warn "Fail to unzip $ball"
+    }
 }
 
-___x_cmd_pkg_install___install(){
-    :
-    # get install script
-    # eval install script
+
+___x_cmd_pkg_install___get_install_script(){
+    : get the install script
+
 }
 
 ___x_cmd_pkg_install(){
     ___x_cmd_pkg_install___download "$@" || return
-    ___x_cmd_pkg_install___unzip    "$@" || return
-    ___x_cmd_pkg_install___install  "$@"
+    if script="$(___x_cmd_pkg_install___get_install_script)"; then
+        eval "$script"
+    else
+        ___x_cmd_pkg_install___unzip    "$@" || return
+    fi
 }
 
 ___x_cmd_pkg_reinstall(){
diff --git a/lib/util b/lib/util
--- a/lib/util
+++ b/lib/util
@@ -36,26 +36,83 @@ ___x_cmd_pkg_post_script(){
     local version="${3:?rovide version}"
 }
 
+___x_cmd_pkg_osarch(){
+    if [ -z "$___X_CMD_PKG_OSARCH" ]; then
+        ___X_CMD_PKG_OSARCH="$(os arch)/$(os name)"
+    fi
+    printf "%s\n" "$___X_CMD_PKG_OSARCH"
+}
+
 
 # Get bin list if zero argument
 # Display path if arguments provided
 # _bin_url__
 # _bin_url_cn
-___x_cmd_pkg___bin_url(){
+___x_cmd_pkg___bin_url_list(){
     local pkg_name="${1:?Provide pkg name}"
-    local osarch="${2:?osarch as filter}"
-    local version="${3:?rovide version}"
+    local version="${2:?rovide version}"
+    local osarch="${3:-${___X_CMD_PKG_OSARCH:-$(___x_cmd_pkg_osarch)}}"
 
-    local url_list
-    url_list="$(___x_cmd_pkg___all_info "${pkg_name}" | awk \
+    ___x_cmd_pkg___all_info "${pkg_name}" | awk \
+        -v osarch="$osarch" \
+        -v version="$version" \
         -f "$___X_CMD_ROOT_MOD/awk/lib/default.awk" \
         -f "$___X_CMD_ROOT_MOD/awk/lib/jqparse.awk" \
         -f "awk/pkg.jobj.awk" \
-        -f "awk/pkg.lsversion.awk")"
+        -f "awk/pkg.lsversion.awk"
+
+}
+
+___x_cmd_pkg_download(){
+    local pkg_name="${1:?Provide pkg name}"
+    local version="${2:?rovide version}"
+
+    local url_list
+    url_list="$(___x_cmd_pkg___bin_url_list "$@")"
 
     local url
+    local ball
     while read -r url; do
-        :
+        ball="$___X_CMD_PKG_DOWNLOAD_PATH/$pkg_name/$version"
+        # Check MD5Sum. Whether it is already exists
+        ___x_cmd_httpget "$url" "$ball" || {
+            pkg:warn "Fail to download from $url"
+            continue
+        }
+        # Check MD5Sum. If not. Deleted
+        x uz "$ball" "$___X_CMD_PKG_INSTALL_PATH/$pkg_name/$version" || {
+            pkg:warn "Fail to unzip from $"
+            continue
+        }
+
+    done <<A
+$url_list
+A
+
+}
+
+___x_cmd_pkg_download(){
+    local pkg_name="${1:?Provide pkg name}"
+    local version="${2:?rovide version}"
+
+    local url_list
+    url_list="$(___x_cmd_pkg___bin_url_list "$@")"
+
+    local url
+    local ball
+    while read -r url; do
+        ball="$___X_CMD_PKG_DOWNLOAD_PATH/$pkg_name/$version"
+        # Check MD5Sum. Whether it is already exists
+        ___x_cmd_httpget "$url" "$ball" || {
+            pkg:warn "Fail to download from $url"
+            continue
+        }
+        # Check MD5Sum. If not. Deleted
+        x uz "$ball" "$___X_CMD_PKG_INSTALL_PATH/$pkg_name/$version" || {
+            pkg:warn "Fail to unzip from $"
+            continue
+        }
+
     done <<A
 $url_list
 A
