...

diff --git a/lib/install b/lib/install
--- a/lib/install
+++ b/lib/install
@@ -1,4 +1,38 @@
 
+___x_cmd_pkg_install(){
+    ___x_cmd_pkg_install___download "$@" || return
+    if script="$(___x_cmd_pkg_install___get_install_script)"; then
+        eval "$script"
+    else
+        ___x_cmd_pkg_install___unzip    "$@" || return
+    fi
+}
+
+___x_cmd_pkg_reinstall(){
+    :
+}
+
+
+___x_cmd_pkg_install___get_install_script(){
+    : get the install script
+
+}
+
+# This is default
+___x_cmd_pkg_install___unzip(){
+    local pkg_name="${1:?Provide pkg name}"
+    local version="${2:?rovide version}"
+
+    local ball="$___X_CMD_PKG_DOWNLOAD_PATH/$pkg_name/$version"
+    local tgt="$___X_CMD_PKG_INSTALL_PATH/$pkg_name/$version"
+
+    x uz "$ball" "$tgt" || {
+        pkg:warn "Fail to unzip $ball"
+    }
+}
+
+
+
 # Get bin list if zero argument
 # Display path if arguments provided
 # _bin_url__
@@ -39,36 +73,3 @@ $url_list
 A
 
 }
-
-# This is default
-___x_cmd_pkg_install___unzip(){
-    local pkg_name="${1:?Provide pkg name}"
-    local version="${2:?rovide version}"
-
-    local ball="$___X_CMD_PKG_DOWNLOAD_PATH/$pkg_name/$version"
-    local tgt="$___X_CMD_PKG_INSTALL_PATH/$pkg_name/$version"
-
-    x uz "$ball" "$tgt" || {
-        pkg:warn "Fail to unzip $ball"
-    }
-}
-
-
-___x_cmd_pkg_install___get_install_script(){
-    : get the install script
-
-}
-
-___x_cmd_pkg_install(){
-    ___x_cmd_pkg_install___download "$@" || return
-    if script="$(___x_cmd_pkg_install___get_install_script)"; then
-        eval "$script"
-    else
-        ___x_cmd_pkg_install___unzip    "$@" || return
-    fi
-}
-
-___x_cmd_pkg_reinstall(){
-    :
-}
-
