feat(pkg): ls installed

diff --git a/lib/main b/lib/main
--- a/lib/main
+++ b/lib/main
@@ -22,6 +22,7 @@
 #         -f "awk/pkg.lsversion.awk"
 # }
 
+xrc p7zip
 ___x_cmd_pkg___which_p7zip()(
     ___x_cmd_mkdirp "$___X_CMD_PKG_RAWPATH"
 
@@ -37,10 +38,11 @@ ___x_cmd_pkg___which_p7zip()(
         pkg:info "Deflate the all.7z"
         x rmrf "$___X_CMD_PKG_RAWPATH"
         ___x_cmd_mkdirp "$___X_CMD_PKG_RAWPATH"
-        if ! cd "${p7zip%/*}" && cp all.7z raw/all.7z && cd raw && x uz all.7z 1>/dev/null && x rmrf all.7z; then
-            x:error "Deflation failure."
-            x rmrf "$p7zip"
-        fi
+        # if ! cd "${p7zip%/*}" && cp all.7z raw/all.7z && cd raw && p7zd x all.7z 1>/dev/null && x rmrf all.7z; then
+        #     x:error "Deflation failure."
+        #     x rmrf "$p7zip"
+        # fi
+        cd "${p7zip%/*}" && cp all.7z raw/all.7z && cd raw && p7zd x all.7z 1>/dev/null && rm all.7z
     fi
 )
 
