...

diff --git a/lib/main b/lib/main
--- a/lib/main
+++ b/lib/main
@@ -25,7 +25,10 @@ ___x_cmd_pkg___which_p7zip(){
         pkg:info "Deflate the all.7z"
         x rmrf "$___X_CMD_PKG_RAWPATH"
         ___x_cmd_mkdirp "$___X_CMD_PKG_RAWPATH"
-        cd "${p7zip%/*}" && cp all.7z raw/all.7z && cd raw && x uz all.7z 1>/dev/null && rm all.7z
+        if ! cd "${p7zip%/*}" && cp all.7z raw/all.7z && cd raw && x uz all.7z 1>/dev/null && x rmrf all.7z; then
+            x:error "Deflation failure."
+            x rmrf "$p7zip"
+        fi
     fi
 }
 
