...

diff --git a/.x-cmd/smoke b/.x-cmd/smoke
--- a/.x-cmd/smoke
+++ b/.x-cmd/smoke
@@ -10,22 +10,33 @@ try_pkg(){
         x pkg install "$name" "$version"
         x pkg activate "$name"
 
-        x pkg _test "$name"
+        ___x_cmd_pkg__smoke "$name"
     )
 }
 
 smoke(){
-    local name; local version
-    local IFS; while read -r name version; do
-        try_pkg "$name" "$version"
-    done <<A
-jq
-yq
-fd
-rg
-ffmpeg
-A
+appandversion="jq 1.6-dirty
+yq 4.15.1
+fd v8.3.2
+rg 13.0.0
+ffmpeg N-105323-gdd17c86aa1-tessus
+"
 
+    local IFS="  "
+    local name; local version
+    printf "%s" "$appandversion" |  while read -r name version; do
+        try_pkg "$name" "$version"
+    done
+
+}
+
+___x_cmd_pkg__smoke(){
+    (
+    cd "$___X_CMD_PKG_RAWPATH" || return
+    if  ! . "./"*"/$name/.x-cmd/smoke.sh" ; then
+        pkg:error "source smoke.sh failed"
+    fi
+    )
 }
 
 smoke
