fix

diff --git a/lib/mutate/download b/lib/mutate/download
--- a/lib/mutate/download
+++ b/lib/mutate/download
@@ -16,7 +16,9 @@ ___x_cmd_pkg_download(){
     local sb_app
     ___x_cmd_pkg___static_build_attr "$name" "$version" "$osarch"
     if [ -n "$sb_repo" ] && [ -n "$sb_app" ]; then
-        ___x_cmd_pkg_download_file___from_static_build_and_deflate "$sb_repo" "$sb_app" "$version" || pkg:error "Download static-build file failed" ; return 1
+        ___x_cmd_pkg_download_file___from_static_build_and_deflate "$sb_repo" "$sb_app" "$version" ||  {
+            pkg:error "Download static-build file failed" ; return 1
+        }
         return
     fi
 
@@ -31,7 +33,9 @@ ___x_cmd_pkg_download(){
     ___x_cmd_pkg___attr "$name" "$version" "$osarch" "md5,sha1,sha256,sha512,file_suffix"
     local url
     local ball="$___X_CMD_PKG_DOWNLOAD_PATH/$name/$version.$file_suffix"
-    mkdir -p "$___X_CMD_PKG_DOWNLOAD_PATH/$name" || pkg:error "Create $___X_CMD_PKG_DOWNLOAD_PATH/$name failed" ; return 1
+    mkdir -p "$___X_CMD_PKG_DOWNLOAD_PATH/$name" || {
+            pkg:error "Create $___X_CMD_PKG_DOWNLOAD_PATH/$name failed" ; return 1
+        }
     pkg:debug "Download $name $version url_list: $url_list ball: $ball"
 
 
diff --git a/lib/mutate/install b/lib/mutate/install
--- a/lib/mutate/install
+++ b/lib/mutate/install
@@ -22,7 +22,9 @@ ___x_cmd_pkg_install(){
         local ball="$___X_CMD_PKG_DOWNLOAD_PATH/$name/$version.$file_suffix"
         pkg:info "Running $script_path after download $name $version"
         pkg:debug "name: $name version: $version osarch: $osarch file_suffix: $file_suffix ball: $ball bin_path: $bin_path"
-        . "$script_path" || pkg:error "Source $script_path failed" ; return 1
+        . "$script_path" || {
+            pkg:error "Source $script_path failed" ; return 1
+            }
         return 0
     else
         local sb_repo sb_app
@@ -49,13 +51,17 @@ ___x_cmd_pkg_install(){
 
     if [ -e "$ball" ]; then
         pkg:info "Remove $ball"
-        x rmrf "$ball" || pkg:error "Remove $ball failed "; return 1
+        x rmrf "$ball" || {
+            pkg:error "Remove $ball failed "; return 1
+        }
     fi
     if ! [ -d "$install_path" ];then
         pkg:warn "This $name $version is no exist."
     else
         pkg:info "Uninstalling $name $version"
-        x rmrf "$install_path" || pkg:error "Remove $install_path failed "; return 1
+        x rmrf "$install_path" || {
+            pkg:error "Remove $install_path failed "; return 1
+        }
     fi
  }
 
@@ -72,7 +78,9 @@ ___x_cmd_pkg_reinstall(){
     pkg:debug "ball: $ball"
     if [ -f "$ball" ]; then
         pkg:info "Delete $ball and reinstall $name $version"
-        x rmrf "$ball" || pkg:error "Remove $ball failed" ; return 1
+        x rmrf "$ball" || {
+            pkg:error "Remove $ball failed" ; return 1
+        }
     fi
     ___x_cmd_pkg_install "$@" || return 1
     # Delete the installation. Re unpack or running the installation script ?
@@ -103,11 +111,19 @@ ___x_cmd_pkg_install___unzip(){
         x uz "$ball" "$unpack_dir" 1>/dev/null || {
             pkg:error "Fail to unzip $ball" ; return 1
         }
-        x rmrf "$tgt" || pkg:error "Remove $tgt failed "; return 1
-        mkdir -p "$tgt" || pkg:error "create $tgt directory failed"; return 1
+        x rmrf "$tgt" || {
+            pkg:error "Remove $tgt failed "; return 1
+        }
+        mkdir -p "$tgt" || {
+            pkg:error "create $tgt directory failed"; return 1
+        }
         pkg:debug "Moving $unpack_dir to $tgt"
-        mv -f "$unpack_dir"/*/* "$tgt" || pkg:error "Moved file of $unpack_dir to $tgt failed" ; return 1
-        x rmrf "$unpack_dir" || pkg:error "Remove $ball failed" ; return 1
+        mv -f "$unpack_dir"/*/* "$tgt" || {
+            pkg:error "Moved file of $unpack_dir to $tgt failed" ; return 1
+        }
+        x rmrf "$unpack_dir" || {
+            pkg:error "Remove $ball failed" ; return 1
+        }
     else
         pkg:info "Unpack: $ball to $tgt"
         x uz "$ball" "$tgt"  || {
