fix

diff --git a/lib/mutate/install b/lib/mutate/install
--- a/lib/mutate/install
+++ b/lib/mutate/install
@@ -8,7 +8,7 @@ ___x_cmd_pkg_install(){
     local osarch="${3:-${___X_CMD_PKG_OSARCH:-$(___x_cmd_pkg_osarch)}}"
     [ -n "$version" ] || return
 
-    ___x_cmd_pkg_download "$name" "$version" "$osarch" || return
+    ___x_cmd_pkg_download "$name" "$version" "$osarch" || return 1
     local script_path
     if script_path="$(___x_cmd_pkg___get_script_path "$name" "$version" "$osarch" install)"; then
         local bin_path
@@ -22,17 +22,17 @@ ___x_cmd_pkg_install(){
         local ball="$___X_CMD_PKG_DOWNLOAD_PATH/$name/$version.$file_suffix"
         pkg:info "Running $script_path after download $name $version"
         pkg:debug "name: $name version: $version osarch: $osarch file_suffix: $file_suffix ball: $ball bin_path: $bin_path"
-        . "$script_path"
+        . "$script_path" || pkg:error "Source $script_path failed" ; return 1
         return 0
     else
         local sb_repo sb_app
-        ___x_cmd_pkg___static_build_attr "$name" "$version" "$osarch"
+        ___x_cmd_pkg___static_build_attr "$name" "$version" "$osarch" || return 1
         if [ -n "$sb_repo" ] && [ -n "$sb_app" ]; then
             pkg:debug "static-build return 0"
             return 0
         fi
 
-        ___x_cmd_pkg_install___unzip "$name" "$version" "$osarch" || return
+        ___x_cmd_pkg_install___unzip "$name" "$version" "$osarch" || return 1
     fi
 }
 
@@ -49,13 +49,13 @@ ___x_cmd_pkg_install(){
 
     if [ -e "$ball" ]; then
         pkg:info "Remove $ball"
-        x rmrf "$ball"
+        x rmrf "$ball" || pkg:error "Remove $ball failed "; return 1
     fi
     if ! [ -d "$install_path" ];then
         pkg:warn "This $name $version is no exist."
     else
         pkg:info "Uninstalling $name $version"
-        x rmrf "$install_path"
+        x rmrf "$install_path" || pkg:error "Remove $install_path failed "; return 1
     fi
  }
 
@@ -72,9 +72,9 @@ ___x_cmd_pkg_reinstall(){
     pkg:debug "ball: $ball"
     if [ -f "$ball" ]; then
         pkg:info "Delete $ball and reinstall $name $version"
-        x rmrf "$ball"
+        x rmrf "$ball" || pkg:error "Remove $ball failed" ; return 1
     fi
-    ___x_cmd_pkg_install "$@"
+    ___x_cmd_pkg_install "$@" || return 1
     # Delete the installation. Re unpack or running the installation script ?
 }
 
@@ -101,16 +101,17 @@ ___x_cmd_pkg_install___unzip(){
         local unpack_dir="$___X_CMD_PKG_DOWNLOAD_PATH/$name/$version"
         pkg:debug "Unpack: $ball to $unpack_dir"
         x uz "$ball" "$unpack_dir" 1>/dev/null || {
-            pkg:warn "Fail to unzip $ball"
+            pkg:error "Fail to unzip $ball" ; return 1
         }
-        x rmrf "$tgt"; mkdir -p "$tgt"
+        x rmrf "$tgt" || pkg:error "Remove $tgt failed "; return 1
+        mkdir -p "$tgt" || pkg:error "create $tgt directory failed"; return 1
         pkg:debug "Moving $unpack_dir to $tgt"
-        mv -f "$unpack_dir"/*/* "$tgt"
-        x rmrf "$unpack_dir"
+        mv -f "$unpack_dir"/*/* "$tgt" || pkg:error "Moved file of $unpack_dir to $tgt failed" ; return 1
+        x rmrf "$unpack_dir" || pkg:error "Remove $ball failed" ; return 1
     else
         pkg:info "Unpack: $ball to $tgt"
         x uz "$ball" "$tgt"  || {
-            pkg:warn "Fail to unzip $ball"
+            pkg:error "Fail to unzip $ball"; return 1
         }
     fi
     pkg:info "Finish unpack $name $version to $tgt"
